learning_template/TemplateApp/urls.py
from django.conf.urls import url
from TemplateApp import views

app_name = 'TemplateApp'

urlpatterns = [
    url(r'^relative/$', views.relative, name='relative' ),
    url(r'^other/', views.other, name='other')
]

learning_template/learning_template/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from TemplateApp import views

urlpatterns = [
    url(r'^$',views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^TemplateApp/', include('TemplateApp.urls')),
]

learning_template/TemplateApp/models.py
from django.db import models

# Create your models here.

learning_template/TemplateApp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {'text': 'Hello i\'am motailab', 'number': 50}
    return render(request, 'app/index.html', context)

def other(request):
    return render(request, 'app/other.html')

def relative(request):
    return render(request, 'app/relative_url_templates.html')

learning_template/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">    
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Navbar</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'TemplateApp:other' %}">other</a>
            </li>
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'TemplateApp:relative' %}">relative</a>
            </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>
</body>
</html>

learning_template/templates/app/index.html
<!DOCTYPE html>
{% extends 'app/base.html' %}
    {% block body_block %}
        <h1>welcome to home guys</h1>
        <a href="{% url 'TemplateApp:other' %}">Other.html</a>
        <a href="{% url 'TemplateApp:relative' %}">Relative.html</a>
        <h3>Showing Context</h3>
        <hr>
        {{ text|lower }}
        {{ number|add:"83" }}
    {% endblock %}

learning_template/templates/app/other.html
{% extends 'app/base.html' %}

{% block body_block %}
    <h1>Welcome To Other Html Template</h1>
    <a href="/">Go Back</a>
{% endblock %}

learning_template/templates/app/relative_url_templates.html
<!DOCTYPE html>
{% extends 'app/base.html' %}
    {% block body_block %}
        <h1>Welcome To Relative Url Html</h1>
        <a href="/">Home</a>
    {% endblock %}